package com.android.dazhihui.a;

public abstract class f
{
  public static final String A;
  public static final String B;
  public static final String C;
  public static final String D;
  public static final String E;
  public static final String F;
  public static final String G;
  public static final String H;
  public static final String I;
  public static final String J;
  public static final String K;
  public static final String L;
  public static final String M;
  public static final String N;
  public static final String O;
  public static final String P;
  public static final String Q;
  public static final String R;
  public static final String S;
  public static final String T;
  public static final String U;
  public static final String V;
  public static final String W;
  public static final String X;
  public static final String Y;
  public static final String Z;
  public static final String[] a;
  public static final String aA = "http://mpay.gw.com.cn/micropayw/jsp/pay/dzhproduct/doubleWarMethodRmbIndex.jsp?DZHSPECIAL=32";
  public static final String aB = "http://mpay.gw.com.cn/micropayw/jsp/pay/dzhproduct/dSignalRmbIndex.jsp?DZHSPECIAL=32";
  public static final String aC = "http://mpay.gw.com.cn/micropayw/jsp/pay/dzhproduct/paySuccess.jsp";
  public static final String aa;
  public static final String ab;
  public static final String ac;
  public static final String ad;
  public static final String ae;
  public static final String af;
  public static final String ag;
  public static final String ah;
  public static final String ai;
  public static final String aj;
  public static final String ak;
  public static final String al;
  public static final String am;
  public static final String an;
  public static final String ao;
  public static final String ap;
  public static final String aq;
  public static final String ar;
  public static final String as;
  public static final String at;
  public static final String au;
  public static final String av;
  public static final String aw;
  public static final String ax;
  public static final String ay;
  public static final String az;
  public static final String b;
  public static final String c;
  public static final String d;
  public static final String e;
  public static final String f;
  public static final String g;
  public static final String h;
  public static final String i;
  public static final String j;
  public static final String k;
  public static final String l;
  public static final String m;
  public static final String n;
  public static final String o;
  public static final String p;
  public static final String q;
  public static final String r;
  public static final String s;
  public static final String t;
  public static final String u;
  public static final String v;
  public static final String w;
  public static final String x;
  public static final String y;
  public static final String z;
  
  static
  {
    if ("formal".equals("beta"))
    {
      a = new String[] { "180.169.10.229:12345", "180.169.10.229:22345" };
      ax = "http://10.15.108.155:8313/dzh?DZHSPECIAL=32";
      as = "http://rebo.yundzh.com/gzlist?DZHSPECIAL=32";
      au = "http://rebobeta.gw.com.cn/activity?DZHSPECIAL=32";
      at = "http://rebo.yundzh.com/wap/style/msg/hitOpinion/html/index.html";
      i = "http://rebobeta.gw.com.cn/wap/data/hit/video_Bar845.json";
      b = "https://ibeta.gw.com.cn/UserCenter/page/account/accoutManage?accessToken=";
      c = "http://app.top500.cn";
      d = "https://i.gw.com.cn/UserCenter/page/account/forgetPass?source=5&DZHSPECIAL=572";
      e = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_821.json";
      f = "http://mnewsbeta.gw.com.cn/wap/data/mobileconfig/menu/menu_plan832.json";
      g = "http://mnewsbeta.gw.com.cn/wap/data/mobileconfig/menu/left_menu845.json";
      h = "http://180.153.251.42:18080/star";
      j = "http://v2.live800.com/live800/chatClient/chatbox.jsp?companyID=484900&jid=3701124606&enterurl=%27+encodeURIComponent(location.href);";
      k = "http://10.15.88.24/image/%1$s/100";
      l = "https://wtsj.xcsc.com/index";
      m = "https://sjxd.xcsc.com/xdtIndex";
      n = "http://10.15.108.157/wap/news/tz.html";
      o = "http://mnews.gw.com.cn/wap/html/temp/template.html?jsonurl=";
      p = "http://mnews.gw.com.cn/wap/html/temp/cjyw.png";
      q = "http://mnews.gw.com.cn/wap/data/mobileconfig/menu/menu_plan801.json";
      r = "http://mnews.gw.com.cn/wap/news/xgfx/ns/nstock_80.json";
      s = "http://mnews.gw.com.cn/wap/news/xgfx/ns/ns_sg.html?kjsg=1";
      t = "http://mnewsalpha.gw.com.cn/wap/data/qs/common/notice840.json";
      u = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_jj_820.json";
      v = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_jy.json";
      w = "http://mnews.gw.com.cn/wap/data/mobileconfig/spc.json";
      x = "http://mnews.gw.com.cn/wap/data/mobileconfig/ttySyl.json";
      y = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/redP_apk800.json";
      z = "http://tfile.gw.com.cn/cdn/back_jptg/tougu.json";
      A = "http://tfile.gw.com.cn/cdn/back_jptg/";
      B = "http://tfile.gw.com.cn/cdn/back_jptg/";
      C = "remind_80.json";
      D = "http://10.15.108.117/micropayw/jsp/zhihb/currencyToLevel2Index.jsp?DZHSPECIAL=33";
      E = "http://htg.yundzh.com/message/multiask?from=mobile";
      F = "&DZHSPECIAL=285";
      G = "http://mnews.gw.com.cn/wap/data/ipad/stock/";
      H = "f10/Cpbd_Gntc.json";
      I = "http://shop.yundzh.com/exchange?DZHSPECIAL=32";
      J = "http://mnews.gw.com.cn/wap/data/mobileconfig/tn/tn.html";
      K = "http://mnews.gw.com.cn/wap/data/mobileconfig/tn/more_810_hs.html?DZHSPECIAL=40";
      L = "http://mnews.gw.com.cn/wap/data/news/txs/page_1.json";
      M = "http://mnews.gw.com.cn/wap/style/kpb/index.html?DZHSPECIAL=33";
      N = "http://mnews.gw.com.cn/wap/data/ipad/stock/";
      O = "http://mnews.gw.com.cn/wap/data/ipad/fund/";
      P = "http://mnews.gw.com.cn/wap/data/mobileconfig/upPull_81.json";
      Q = "http://140.207.227.106:9888/kesb_req";
      R = "http://mnews.gw.com.cn/wap/data/ipad/sector/";
      S = "http://10.15.108.155:8780/friend/shareInfo";
      T = "https://ibeta.gw.com.cn/UserCenter/page/account/register?source=5&DZHSPECIAL=572";
      U = "http://zttz.gw.com.cn/";
      V = "http://mnewsbeta.gw.com.cn/wap/data/mobileconfig/sc845.json";
      W = "http://htg.yundzh.com/message/zdwd?code=";
      X = "http://mnews.gw.com.cn/wap/data/mobileconfig/remind.json";
      Y = "http://mnewsbeta.gw.com.cn/wap/data/hit/present.json";
      Z = "http://rebobeta.gw.com.cn/report";
      aa = "http://rebobeta.gw.com.cn/pm/index";
      ab = "http://rebobeta.gw.com.cn/pm/sendpm";
      ac = "http://10.15.108.157/wap/data/mobileconfig/hotList.json";
      ad = "http://aia.gw.com.cn/index.php?c=robot&DZHSPECIAL=36&a=index&stock=";
      ae = "http://rebobeta.gw.com.cn/pay/prodlist";
      af = "http://rebobeta.gw.com.cn/pay/prodwx";
      ag = "http://rebobeta.gw.com.cn/pay/getorderid?";
      ah = "http://10.15.144.80/user/news";
      ai = ah + "/favorite?";
      aj = ah + "/collect?";
      ak = ah + "/deletefavorite?";
      al = "http://10.15.108.157/wap/style/detail/newsdetail.html?jsonurl=";
      ao = "http://10.15.208.121/richsearch/live/bigv?";
      ap = "http://htg.yundzh.com/friend/grzyun?un=";
      aq = "http://uniformkh.cairenhui.com/DZH/servers.xml";
      am = "http://shop.yundzh.com/level2/rmb?DZHSPECIAL=33";
      ar = "http://10.15.208.121";
      av = "http://10.15.201.198:8082/reboback/zbapply/index.do?vs=1&DZHSPECIAL=257";
      aw = "http://rebo.yundzh.com/index/setpush?DZHSPECIAL=257";
      an = "http://mnewsbeta.gw.com.cn/wap/style/news/stock/html/xsbgg.html?";
      ay = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/level2RmbIndex.jsp?DZHSPECIAL=32";
      az = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/mainCodeTrackRmbIndex.jsp?DZHSPECIAL=32";
      aA = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/doubleWarMethodRmbIndex.jsp?DZHSPECIAL=32";
      aB = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/dSignalRmbIndex.jsp?DZHSPECIAL=32";
      aC = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/paySuccess.jsp";
      return;
    }
    if ("formal".equals("local"))
    {
      a = new String[] { "10.15.107.11:12345" };
      ax = "http://10.15.108.155:8313/dzh?DZHSPECIAL=32";
      as = "http://10.15.108.155:8786/gzlist?DZHSPECIAL=32";
      au = "http://10.15.108.155:8785/activity?DZHSPECIAL=32";
      at = "http://10.15.108.157/wap/style/msg/hitOpinion/html/index.html";
      i = "http://10.15.108.157/wap/data/hit/video_Bar845.json";
      b = "http://qqtest.gw.com.cn/UserCenter/page/account/accoutManage?accessToken=";
      c = "http://app.top500.cn";
      d = "https://i.gw.com.cn/UserCenter/page/account/forgetPass?source=5&DZHSPECIAL=572";
      e = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_821.json";
      f = "http://10.15.108.157/wap/data/mobileconfig/menu/menu_plan832.json";
      g = "http://10.15.108.157/wap/data/mobileconfig/menu/left_menu845.json";
      h = "http://180.153.251.42:18080/star";
      j = "http://v2.live800.com/live800/chatClient/chatbox.jsp?companyID=484900&jid=3701124606&enterurl=%27+encodeURIComponent(location.href);";
      k = "http://10.15.201.105/image/%1$s/100";
      l = "https://wtsj.xcsc.com/index";
      m = "https://sjxd.xcsc.com/xdtIndex";
      n = "http://10.15.108.157/wap/news/tz.html";
      o = "http://mnews.gw.com.cn/wap/html/temp/template.html?jsonurl=";
      p = "http://mnews.gw.com.cn/wap/html/temp/cjyw.png";
      q = "http://mnews.gw.com.cn/wap/data/mobileconfig/menu/menu_plan801.json";
      r = "http://mnews.gw.com.cn/wap/news/xgfx/ns/nstock_80.json";
      s = "http://mnews.gw.com.cn/wap/news/xgfx/ns/ns_sg.html?kjsg=1";
      t = "http://mnewsalpha.gw.com.cn/wap/data/qs/common/notice.json";
      u = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_jj_820.json";
      v = "http://10.15.108.157/wap/data/mobileconfig/navigation/navigat_jy.json";
      w = "http://mnews.gw.com.cn/wap/data/mobileconfig/spc.json";
      x = "http://mnews.gw.com.cn/wap/data/mobileconfig/ttySyl.json";
      y = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/redP_apk800.json";
      z = "http://tfile.gw.com.cn/cdn/back_jptg/tougu.json";
      A = "http://tfile.gw.com.cn/cdn/back_jptg/";
      B = "http://tfile.gw.com.cn/cdn/back_jptg/";
      C = "remind_80.json";
      D = "http://10.15.108.117/micropayw/jsp/zhihb/currencyToLevel2Index.jsp?DZHSPECIAL=33";
      E = "http://htg.yundzh.com/message/multiask?from=mobile";
      F = "&DZHSPECIAL=285";
      G = "http://mnews.gw.com.cn/wap/data/ipad/stock/";
      H = "f10/Cpbd_Gntc.json";
      I = "http://shop.yundzh.com/exchange?DZHSPECIAL=32";
      J = "http://mnews.gw.com.cn/wap/data/mobileconfig/tn/tn.html";
      K = "http://mnews.gw.com.cn/wap/data/mobileconfig/tn/more_810_hs.html?DZHSPECIAL=40";
      L = "http://mnews.gw.com.cn/wap/data/news/txs/page_1.json";
      M = "http://mnews.gw.com.cn/wap/style/kpb/index.html?DZHSPECIAL=33";
      N = "http://mnews.gw.com.cn/wap/data/ipad/stock/";
      O = "http://mnews.gw.com.cn/wap/data/ipad/fund/";
      P = "http://mnews.gw.com.cn/wap/data/mobileconfig/upPull_81.json";
      Q = "http://140.207.227.106:9888/kesb_req";
      R = "http://mnews.gw.com.cn/wap/data/ipad/sector/";
      S = "http://10.15.108.155:8780/friend/shareInfo";
      T = "http://qqtest.gw.com.cn/UserCenter/page/account/register?source=5&DZHSPECIAL=572";
      U = "http://zttz.gw.com.cn/";
      V = "http://10.15.108.157/wap/data/mobileconfig/sc845.json";
      W = "http://htg.yundzh.com/message/zdwd?code=";
      X = "http://mnews.gw.com.cn/wap/data/mobileconfig/remind.json";
      Y = "http://10.15.108.157/wap/data/hit/present.json";
      Z = "http://rebobeta.gw.com.cn/report";
      aa = "http://10.15.108.155:8785/pm/index";
      ab = "http://rebobeta.gw.com.cn/pm/sendpm";
      ac = "http://10.15.108.157/wap/data/mobileconfig/hotList.json";
      ad = "http://10.15.108.155:8644/index.php?c=robot&DZHSPECIAL=36&a=index&stock=";
      ae = "http://10.15.108.155:8785/pay/prodlist";
      af = "http://10.15.108.155:8785/pay/prodwx";
      ag = "http://10.15.108.155:8785/pay/getorderid?";
      ah = "http://10.15.144.80/user/news";
      ai = ah + "/favorite?";
      aj = ah + "/collect?";
      ak = ah + "/deletefavorite?";
      al = "http://10.15.108.157/wap/style/detail/newsdetail.html?jsonurl=";
      ao = "http://10.15.144.80/richsearch/live/bigv?";
      ap = "http://htg.yundzh.com/friend/grzyun?un=";
      aq = "http://uniformkh.cairenhui.com/DZH/servers.xml";
      am = "http://shop.yundzh.com/level2/rmb?DZHSPECIAL=33";
      ar = "http://10.15.144.80";
      av = "http://10.15.108.154:8426/reboback/zbapply/index.do?vs=1&DZHSPECIAL=257";
      aw = "http://rebo.yundzh.com/index/setpush?DZHSPECIAL=257";
      an = "http://10.15.108.157/wap/style/news/stock/html/xsbgg.html?";
      ay = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/level2RmbIndex.jsp?DZHSPECIAL=32";
      az = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/mainCodeTrackRmbIndex.jsp?DZHSPECIAL=32";
      aA = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/doubleWarMethodRmbIndex.jsp?DZHSPECIAL=32";
      aB = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/dSignalRmbIndex.jsp?DZHSPECIAL=32";
      aC = "http://114.80.158.16/micropayw/jsp/pay/dzhproduct/paySuccess.jsp";
      return;
    }
    a = new String[] { "222.73.34.8:12346", "222.73.103.42:12346", "61.151.252.4:12346", "61.151.252.14:12346" };
    ax = "http://10.15.108.155:8313/dzh?DZHSPECIAL=32";
    as = "http://rebo.yundzh.com/vbgzlist?DZHSPECIAL=32";
    au = "http://rebo.yundzh.com/activity?DZHSPECIAL=32";
    at = "http://rebo.yundzh.com/wap/style/msg/hitOpinion/html/index.html";
    i = "http://rebo.yundzh.com/wap/data/hit/video_Bar845.json";
    b = "http://i.gw.com.cn/UserCenter/page/account/accoutManage?accessToken=";
    c = "http://app.top500.cn";
    d = "https://i.gw.com.cn/UserCenter/page/account/forgetPass?source=5&DZHSPECIAL=572";
    e = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_821.json";
    f = "http://mnews.gw.com.cn/wap/data/mobileconfig/menu/menu_plan832.json";
    g = "http://mnews.gw.com.cn/wap/data/mobileconfig/menu/left_menu845.json";
    h = "http://180.153.251.42:18080/star";
    j = "http://v2.live800.com/live800/chatClient/chatbox.jsp?companyID=484900&jid=3701124606&enterurl=%27+encodeURIComponent(location.href);";
    k = "http://cimage.gw.com.cn/image/%1$s/100";
    l = "https://wtsj.xcsc.com/index";
    m = "https://sjxd.xcsc.com/xdtIndex";
    n = "http://10.15.108.157/wap/news/tz.html";
    o = "http://mnews.gw.com.cn/wap/html/temp/template.html?jsonurl=";
    p = "http://mnews.gw.com.cn/wap/html/temp/cjyw.png";
    q = "http://mnews.gw.com.cn/wap/data/mobileconfig/menu/menu_plan801.json";
    r = "http://mnews.gw.com.cn/wap/news/xgfx/ns/nstock_80.json";
    s = "http://mnews.gw.com.cn/wap/news/xgfx/ns/ns_sg.html?kjsg=1";
    t = "http://mnews.gw.com.cn/wap/data/qs/common/notice845.json";
    u = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_jj_820.json";
    v = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/navigat_jy.json";
    w = "http://mnews.gw.com.cn/wap/data/mobileconfig/spc.json";
    x = "http://mnews.gw.com.cn/wap/data/mobileconfig/ttySyl.json";
    y = "http://mnews.gw.com.cn/wap/data/mobileconfig/navigation/redP_apk800.json";
    z = "http://tfile.gw.com.cn/cdn/back_jptg/tougu.json";
    A = "http://tfile.gw.com.cn/cdn/back_jptg/";
    B = "http://tfile.gw.com.cn/cdn/back_jptg/";
    C = "remind_80.json";
    D = "http://10.15.108.117/micropayw/jsp/zhihb/currencyToLevel2Index.jsp?DZHSPECIAL=33";
    E = "http://htg.yundzh.com/message/multiask?from=mobile";
    F = "&DZHSPECIAL=285";
    G = "http://mnews.gw.com.cn/wap/data/ipad/stock/";
    H = "f10/Cpbd_Gntc.json";
    I = "http://shop.yundzh.com/exchange?DZHSPECIAL=32";
    J = "http://mnews.gw.com.cn/wap/data/mobileconfig/tn/tn.html";
    K = "http://mnews.gw.com.cn/wap/data/mobileconfig/tn/more_810_hs.html?DZHSPECIAL=40";
    L = "http://mnews.gw.com.cn/wap/data/news/txs/page_1.json";
    M = "http://mnews.gw.com.cn/wap/style/kpb/index.html?DZHSPECIAL=33";
    N = "http://mnews.gw.com.cn/wap/data/ipad/stock/";
    O = "http://mnews.gw.com.cn/wap/data/ipad/fund/";
    P = "http://mnews.gw.com.cn/wap/data/mobileconfig/upPull_81.json";
    Q = "http://140.207.227.106:9888/kesb_req";
    R = "http://mnews.gw.com.cn/wap/data/ipad/sector/";
    S = "http://htg.yundzh.com/friend/shareInfo";
    T = "https://i.gw.com.cn/UserCenter/page/account/register?source=5&DZHSPECIAL=572";
    U = "http://zttz.gw.com.cn/";
    V = "http://mnews.gw.com.cn/wap/data/mobileconfig/sc845.json";
    W = "http://htg.yundzh.com/message/zdwd?code=";
    X = "http://mnews.gw.com.cn/wap/data/mobileconfig/remind.json";
    Y = "http://rebo.yundzh.com/wap/data/hit/present841.json";
    Z = "http://rebo.yundzh.com/report";
    aa = "http://rebo.yundzh.com/pm/index";
    ab = "http://rebo.yundzh.com/pm/sendpm";
    ac = "http://mnews.gw.com.cn/wap/data/mobileconfig/hotList.json";
    ad = "http://aia.gw.com.cn/index.php?c=robot&DZHSPECIAL=36&a=index&stock=";
    ae = "http://rebo.yundzh.com/pay/prodlist";
    af = "http://rebo.yundzh.com/pay/prodwx";
    ag = "http://rebo.yundzh.com/pay/getorderid?";
    ah = "http://v2.yundzh.com/user/news";
    ai = ah + "/favorite?";
    aj = ah + "/collect?";
    ak = ah + "/deletefavorite?";
    al = "http://mnews.gw.com.cn/wap/style/detail/newsdetail.html?jsonurl=";
    ao = "http://so.yundzh.com/richsearch/live/bigv?";
    ap = "http://htg.yundzh.com/friend/grzyun?un=";
    aq = "http://uniformkh.cairenhui.com/DZH/servers.xml";
    am = "http://shop.yundzh.com/level2/rmb?DZHSPECIAL=33";
    ar = "http://v2.yundzh.com";
    av = "http://mnews.gw.com.cn/wap/html/wobo/index.html";
    aw = "http://rebo.yundzh.com/index/setpush?DZHSPECIAL=257";
    an = "http://mnews.gw.com.cn/wap/style/news/stock/html/xsbgg.html?";
    ay = "http://mpay.gw.com.cn/micropayw/jsp/pay/dzhproduct/level2RmbIndex.jsp?DZHSPECIAL=32";
    az = "http://mpay.gw.com.cn/micropayw/jsp/pay/dzhproduct/mainCodeTrackRmbIndex.jsp?DZHSPECIAL=32";
  }
}


/* Location:              E:\apk\dazhihui2\classes-dex2jar.jar!\com\android\dazhihui\a\f.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */